name: Deploy
on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: cngei/gitops
          token: ${{ secrets.GITOPS_PUSH_SECRET }}
          ref: master
          path: gitops-repo
          fetch-depth: 0
      - name: Update ArgoCD config and push
        run: |
          cd gitops-repo/keycloak
          sed -i "s|^\([[:space:]]*image: \).*|\1ghcr.io/cngei/kc-theme:${{ github.sha }}|" kc.yaml
          num_files_updated=$(git diff --numstat | wc -l)
          echo "::notice::${num_files_updated} files were updated"
          if (( num_files_updated > 0 )); then
          git config user.name "GitHub Action"
          git config user.email "servizi.informatici@cngei.it"
          git add .
          git commit -m "Action triggered: Updated Keycloak to ${{ github.sha }}"
          git push
          fi
